Repository FriendsOfSymfony/FOSOAuthServerBundle, pull requests merged in 2018-04, with the labels that each got.

#554 The authorize form should be used only if authorize option true.
  DependencyInjection/FOSOAuthServerExtension.php
  Tests/DependencyInjection/FOSOAuthServerExtensionTest.php
Labels: Bug

#553 Custom db driver.
  DependencyInjection/Configuration.php
  DependencyInjection/FOSOAuthServerExtension.php
  Resources/config/oauth.xml
  Resources/doc/custom_db_driver.md
  Resources/doc/index.md
  Tests/DependencyInjection/ConfigurationTest.php
  Tests/DependencyInjection/FOSOAuthServerExtensionTest.php
Labels: Enhancement

#564 Allow overriding authorizeAction's render
  Controller/AuthorizeController.php
Labels: wip/poc

#535 Raise PHPStan's level from 3 to 4
  Form/Model/Authorize.php
  Makefile
  Security/Authentication/Provider/OAuthProvider.php
  Storage/OAuthStorage.php
  Tests/Form/Type/AuthorizeFormTypeTest.php
  Tests/Storage/OAuthStorageTest.php
Labels: Enhancement, PHPStan

#573 Raise PHPStan's level from 5 to 6
  Makefile
  Tests/Form/Handler/AuthorizeFormHandlerTest.php
  phpstan.neon
Labels: Enhancement, PHPStan, wip/poc
